### PR TITLE
Added node-red init script

### PR DESCRIPTION
**Pull request by DaCookie4u**
I took the liberty of adding a nicer node-red startup script which allows for a log and a clean shutdown signal. Since I do a lot of trainings with this device and teaching industry people how to install a custom start script manually takes a lot of time and patience.

The script has been included into the iot2000setup recipe and I hope I updated the bitbake file correctly.

ps: Also not sure whether I am pushing this to the right branch. Couldn't find a contribution guideline.

### CODE REVIEW

**Comment by DaCookie4u** [comment]
Is this project still active?

**Comment by jan-kiszka** [comment]
Oops, thought I replied, but that was to a colleague who wrote something similar as well. So did I, just didn't push it yet. Give me a day, and then we can discuss if something is still missing.

BTW, I also refactored iot2000setup /wrt start scripts significantly.

**Comment by DaCookie4u** [comment]
Awesome, I will wait for your push then.

**Comment by jan-kiszka** [comment]
master now has a proper init script for node-red, with logging as well.

**Pull request closed without merging**
