### PR TITLE
Update yml file to match new kas version 0.13.0

### PR DESCRIPTION
**Pull request by johnson325**
Update yml file to match new kas version 0.13.0

### CODE REVIEW

**Comment by cmhe** [comment]
This makes it incompatible with older kas versions and since you just set 'task' to the default setting 'build' I don't see the benefit here.

**Comment by jan-kiszka** [comment]
Yes, for now, we should only request file version 3 for the upcoming sdk yml file.

**Comment by BaochengSu** [comment]
So people has to update kas before running new build?

I think it would be helpful for people who have already built the image before to know the change of the file version, by writing it down to README file or something like this.

Or if KAS tool can update itself for each build, it would be better.

**Comment by cmhe** [comment]
@BaochengSu: No. This patch was not appied.

**Comment by jan-kiszka** [comment]
What I meant is: add "version: 3" to meta-iot2000-example/sdk-kas.yml only, leaving the other files at the sufficient version 2 dependency.

**Pull request closed without merging**
